name: On Release

on:
  release:
    types:
    - published

jobs:
  bundle-headers:
    name: "Bundle header-only libraries"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v3
      with:
        name: header-only
        path: header-only

  publish-headers:
    name: "Publish header-only libraries alongside release"
    runs-on: ubuntu-latest
    needs: [bundle-headers]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: header-only
        path: header-only
    - uses: softprops/action-gh-release@v1
      with:
        files: header-only/*
