on:
  push:

jobs:
  build:
    name: A job to say hello
    runs-on: ubuntu-latest

    steps:
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/clinder
        with:
          hub-url: https://mybinder.org
          repo: https://gist.github.com/agoose77/fc9557d0505c6976335be43db6fcda90

      # Use the output from the `hello` step
      - run: echo "The URL was ${{ steps.hello.outputs.url }}" and "token ${{ steps.hello.outputs.token }}"
